/**
 * Reading a source SVG as the one path an icon is, and writing that path out as a module.
 *
 * The geometry and the module text are kept apart from the file system on purpose: these are the
 * parts that decide what an icon renders and what the generated module says about it, and they are
 * the parts worth testing without a directory of artwork beside them. `scripts/bundle-icons.ts` is
 * the driver that supplies the SVGs.
 */

/** One icon, as the bundle holds it: a name and the path data drawn for it. */
export interface BundledIcon {
  readonly name: string;
  readonly pathData: string;
}

/**
 * The parts of an SVG an icon is made of, read rather than assumed.
 *
 * Width, height and viewBox are parsed because an icon drawn in a different coordinate system has to
 * be rejected rather than quietly scaled: `Icon` places a path in a viewBox of its own, so artwork
 * exported at another size is not an icon this library can draw.
 */
export interface SvgGeometry {
  readonly width: number;
  readonly height: number;
  readonly viewBox: string;
  readonly pathData: string;
}

/** The side of the square every icon is drawn in, and the canvas a source SVG has to declare. */
const ICON_CANVAS_SIZE = 100;
const ICON_VIEW_BOX = `0 0 ${ICON_CANVAS_SIZE} ${ICON_CANVAS_SIZE}`;

/**
 * Decimal places kept in the bundled path data.
 *
 * A hundredth of a unit in a canvas a hundred units wide is a hundredth of a pixel at any size an
 * icon is drawn at, so three places are the point where the digits stop describing anything visible.
 * The path data of a whole icon set is the largest thing this library ships, so the places past that
 * are worth the rounding.
 */
const PATH_DECIMAL_PRECISION = 3;

/**
 * An icon name is what a caller passes to a `name` prop and what ends up in a DOM id, so it holds
 * nothing that has to be escaped.
 */
const ICON_NAME_PATTERN = /^[a-zA-Z0-9]+$/;

/** A name this library can use as an object key without quoting it. */
const IDENTIFIER_PATTERN = /^[a-zA-Z_$][a-zA-Z0-9_$]*$/;

/** The opening `<svg>` tag, whose attributes describe the canvas the icon is drawn in. */
const SVG_TAG_PATTERN = /<svg\b([^>]*)>/;

/** Every `<path>` element, which is the only element `Icon` knows how to draw. */
const PATH_ELEMENT_PATTERN = /<path\b([^>]*)>/g;

/**
 * One number in path data, exponent included.
 *
 * An SVG exporter writes a small number as `1.51e-4` rather than as fourteen decimal places, and the
 * exponent is part of the number: a pattern that stopped before the `e` would round `1.51e-4` to
 * `1.51-4` and leave a path that draws something else entirely.
 */
const PATH_NUMBER_PATTERN = /-?(?:\d+(?:\.\d+)?|\.\d+)(?:[eE][-+]?\d+)?/g;

/**
 * The documentation comment the generated module carries.
 *
 * It is written here rather than left to the file because the file is rewritten from the SVGs on
 * every run: a comment that lived in the generated file would have to be copied into the generator
 * anyway, and one that lived nowhere would be gone the next time an icon is added.
 */
const MODULE_HEADER = `/**
 * The path \`d\` data of every icon the library ships, keyed by icon name.
 *
 * Generated by \`deno task icons\` from the SVGs beside this file — edit those, not this one. It holds
 * data, not images: {@link Icon} is what builds the \`<svg>\` around a path and points itself at it,
 * and it is also why the element is \`aria-hidden\` with no \`<title>\` of its own — the accessible
 * name is the label of the control around the icon, not anything this data says.
 *
 * {@link IconName} is derived from the keys of this map, so a name here is a name the components can
 * render, and adding an entry here is what adds an icon. {@link IconViewer} reads the same map to
 * show and copy what is available.
 */`;

/** True for a name this library can key an icon by. */
export function isValidIconName(name: string): boolean {
  return ICON_NAME_PATTERN.test(name);
}

/**
 * Reads the geometry of an icon SVG, rejecting anything `Icon` could not draw.
 *
 * @param source - The text of one `.svg` file.
 * @returns The canvas the icon declares and the path data it draws.
 * @throws When the source is not a single path on a 100 by 100 canvas, naming what was found.
 */
export function readSvgGeometry(source: string): SvgGeometry {
  const svgTag = SVG_TAG_PATTERN.exec(source)?.[1];

  if (svgTag === undefined) {
    throw new Error('no <svg> element found');
  }

  const pathElements = [...source.matchAll(PATH_ELEMENT_PATTERN)];
  const pathTag = pathElements.find((element) => element[1] !== undefined)?.[1];

  if (pathTag === undefined || pathElements.length > 1) {
    throw new Error(
      `expected one <path> element and found ${pathElements.length}: an icon is one path, ` +
        'because Icon draws a path and nothing else',
    );
  }

  const pathData = readAttribute(pathTag, 'd')?.trim() ?? '';

  if (pathData === '') {
    throw new Error('the <path> element draws nothing: its d attribute is empty');
  }

  const width = readCanvasSide(svgTag, 'width');
  const height = readCanvasSide(svgTag, 'height');
  const viewBox = readAttribute(svgTag, 'viewBox')?.trim() ?? '';

  if (width !== ICON_CANVAS_SIZE || height !== ICON_CANVAS_SIZE || viewBox !== ICON_VIEW_BOX) {
    throw new Error(
      `an icon is drawn on a ${ICON_CANVAS_SIZE} by ${ICON_CANVAS_SIZE} canvas, and this one ` +
        `declares width="${width}" height="${height}" viewBox="${viewBox}"`,
    );
  }

  return { width, height, viewBox, pathData };
}

/**
 * Rounds the numbers in path data to the precision an icon is drawn at.
 *
 * The rounding is to decimal places rather than to significant digits because the coordinates here
 * are absolute positions in a fixed canvas, and a significant-digit rule would make rounding depend
 * on where in the canvas a number fell. A number too small for the precision becomes `0`, which for
 * the sub-thousandth units an exporter leaves in an arc radius is the point of the rounding.
 *
 * Two printed numbers that would read as one are separated — what came before is a digit and this
 * begins with one — because a boundary that read as a separator in the source can stop doing that
 * when the rounding takes the sign away: round the `-2.25e-4` in `0-2.25e-4-6.2594` and the `0` it
 * prints sits against the `0` before it as `00`, and every parameter behind them shifts. A minus of
 * its own is a separator, so `2.472-3.073` is left as the source wrote it, and a space is always a
 * legal separator in path data.
 *
 * @param pathData - A `d` attribute as written in the source SVG.
 * @returns The same path with every number rounded, and nothing else changed.
 */
export function roundPathData(pathData: string): string {
  let text = '';
  let end = 0;

  for (const match of pathData.matchAll(PATH_NUMBER_PATTERN)) {
    const index = match.index;

    text += pathData.slice(end, index);

    const printed = formatRounded(match[0]);
    if (endsWithDigit(text) && /\d/.test(printed.charAt(0))) text += ' ';

    text += printed;
    end = index + match[0].length;
  }

  return text + pathData.slice(end);
}

/** One number of path data, rounded to {@link PATH_DECIMAL_PRECISION} places and shortest-printed. */
function formatRounded(number: string): string {
  const factor = 10 ** PATH_DECIMAL_PRECISION;
  return String(Math.round(Number(number) * factor) / factor);
}

/** True when the text so far ends in a digit, a place another number could fuse against. */
function endsWithDigit(text: string): boolean {
  return /\d/.test(text.charAt(text.length - 1));
}

/**
 * Renders the bundled icons as the module `src/icons/index.tsx` is.
 *
 * The icons are sorted by name so that regenerating after adding one icon changes one line rather
 * than the whole file, and so that a diff of the generated module reads as the icons it added.
 *
 * @param icons - The icons to bundle, in any order.
 * @returns The complete text of the generated module.
 */
export function renderIconPathModule(icons: readonly BundledIcon[]): string {
  // Compared rather than sorted with `localeCompare`: this file is committed, so its order has to be
  // the same on every machine, and collation is a property of the locale a machine happens to have.
  const sorted = [...icons].sort((left, right) => (left.name < right.name ? -1 : 1));
  const properties = sorted.map((icon) => `  ${renderKey(icon.name)}: '${icon.pathData}',`);

  return `${MODULE_HEADER}\nexport const iconPaths = {\n${properties.join('\n')}\n};\n`;
}

/** The value of one attribute of an element's opening tag. */
function readAttribute(tag: string, name: string): string | undefined {
  return new RegExp(`\\b${name}="([^"]*)"`).exec(tag)?.[1];
}

/**
 * The declared length of one side of the canvas, which has to be a whole number of units.
 *
 * A fractional side is refused rather than rounded: the exporter that wrote it is not the exporter
 * the icon set was drawn for, and the icon it produced would sit in the canvas at a size nobody
 * chose.
 */
function readCanvasSide(svgTag: string, name: 'width' | 'height'): number {
  const declared = readAttribute(svgTag, name) ?? '';

  if (!/^\d+$/.test(declared)) {
    throw new Error(`the <svg> element declares no whole-number ${name}, and says "${declared}"`);
  }

  return Number(declared);
}

/**
 * An object key, quoted when the name is not an identifier on its own.
 *
 * A name is allowed to begin with a digit, which is not something an unquoted key may do; the
 * formatter drops the quotes again for every name that does not need them.
 */
function renderKey(name: string): string {
  return IDENTIFIER_PATTERN.test(name) ? name : `'${name}'`;
}
