import { describe, expect, it } from 'vitest';
import {
  isValidIconName,
  readSvgGeometry,
  renderIconPathModule,
  roundPathData,
} from './icon-bundle';

/** An icon source the way the export tool writes one: one path, on the canvas every icon shares. */
function iconSource(pathData: string, canvas = ''): string {
  return (
    `<svg width="100" height="100" ${canvas}viewBox="0 0 100 100" ` +
    `xmlns="http://www.w3.org/2000/svg"><path d="${pathData}" /></svg>`
  );
}

describe('readSvgGeometry', () => {
  it('reads the canvas and the path of an icon SVG', () => {
    expect(readSvgGeometry(iconSource('m43 5v38h-14v38h38v-14h-38z'))).toEqual({
      width: 100,
      height: 100,
      viewBox: '0 0 100 100',
      pathData: 'm43 5v38h-14v38h38v-14h-38z',
    });
  });

  it('reads a path whose d is not its first attribute', () => {
    const source = iconSource('m0 0h100v100z').replace('<path ', '<path fill="none" ');

    expect(readSvgGeometry(source).pathData).toBe('m0 0h100v100z');
  });

  it('refuses a canvas that is not the one icons are drawn in', () => {
    const source = iconSource('m0 0h24v24z')
      .replace('width="100"', 'width="24"')
      .replace('height="100"', 'height="24"');

    expect(() => readSvgGeometry(source)).toThrow(/drawn on a 100 by 100 canvas/);
  });

  it('refuses an SVG that holds more than one path', () => {
    const source = iconSource('m0 0h10v10z') + iconSource('m10 10h10v10z');

    expect(() => readSvgGeometry(source)).toThrow(/found 2/);
  });

  it('refuses an SVG with a path that draws nothing', () => {
    expect(() => readSvgGeometry(iconSource(''))).toThrow(/draws nothing/);
  });

  it('refuses text that is not an SVG', () => {
    expect(() => readSvgGeometry('not an svg at all')).toThrow(/no <svg> element/);
  });
});

describe('roundPathData', () => {
  it('rounds numbers to three decimal places', () => {
    expect(roundPathData('m5.5452 2.47191-3.0732 25.456')).toBe('m5.545 2.472-3.073 25.456');
  });

  it('rounds a number written in exponent form, sign included', () => {
    expect(roundPathData('c3.9688e-6 6.0e-4-1.3229e-4')).toBe('c0 0.001 0');
  });

  it('separates a zero that rounded away its sign from the number before it', () => {
    // The source held two parameters (`0` and `2.2e-5`); printed back to back they would read as `00`.
    expect(roundPathData('9.5741 0-2.25e-4-6.2594')).toBe('9.574 0 0-6.259');
  });

  it('reprints a fraction that shared its dot with the whole number before it', () => {
    // `9.5741.5` is two parameters (9.5741 and .5); printed back to back they would read as one.
    expect(roundPathData('9.5741.5-3.5001')).toBe('9.574 0.5-3.5');
  });

  it('leaves a path that holds no exponent alone', () => {
    expect(roundPathData('m43 5v38h-38v14h38v38h14v-38h38v-14h-38v-38z')).toBe(
      'm43 5v38h-38v14h38v38h14v-38h38v-14h-38v-38z',
    );
  });
});

describe('isValidIconName', () => {
  it('accepts the letters and digits an icon is keyed by', () => {
    expect(isValidIconName('arrowDown')).toBe(true);
    expect(isValidIconName('network2')).toBe(true);
  });

  it('refuses anything that would have to be escaped in a DOM id', () => {
    for (const name of ['', 'arrow-down', 'arrow down', 'arrowDown!', 'arrowDown\u2019s']) {
      expect(isValidIconName(name)).toBe(false);
    }
  });
});

describe('renderIconPathModule', () => {
  it('writes one property per icon, sorted by name', () => {
    const module = renderIconPathModule([
      { name: 'check', pathData: 'm0 0h10v10z' },
      { name: 'alFind', pathData: 'm10 10' },
    ]);

    expect(module).toContain(
      "export const iconPaths = {\n  alFind: 'm10 10',\n  check: 'm0 0h10v10z',\n};",
    );
  });

  it('quotes a name that is not an identifier on its own', () => {
    const module = renderIconPathModule([{ name: '3d', pathData: 'm0 0' }]);

    expect(module).toContain("'3d': 'm0 0'");
  });

  it('states that the module is generated and where to edit instead', () => {
    expect(renderIconPathModule([])).toContain(
      'Generated by `deno task icons` from the SVGs beside this file',
    );
  });
});
