package main

import (
	"encoding/base64"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

func generate(filename string) {
	fmt.Printf("Generating TS module for %s...\n", filename)

	// Get the current script directory
	currentScriptDirectory, err := os.Getwd()
	if err != nil {
		fmt.Println("Error getting current directory:", err)
		return
	}

	sourceFilePath := filepath.Join(currentScriptDirectory, filename)
	outputFilePath := filepath.Join(currentScriptDirectory, strings.Replace(filename, ".png", "PngBase64.tsx", 1))

	// Read the PNG file
	pngContent, err := os.ReadFile(sourceFilePath)
	if err != nil {
		fmt.Println("Error reading file:", err)
		return
	}

	// Encode the PNG content to Base64
	base64Data := base64.StdEncoding.EncodeToString(pngContent)

	// Generate the TypeScript file content
	generatedFileContent := fmt.Sprintf(
		"// Code generated by convertPngToBase64.go; DO NOT EDIT.\n"+
			"\n"+
			"export const data = 'data:image/png;base64,%s';\n",
		base64Data,
	)

	// Write the generated content to the output file
	err = os.WriteFile(outputFilePath, []byte(generatedFileContent), 0644)
	if err != nil {
		fmt.Println("Error writing file:", err)
		return
	}
}

func main() {
	generate("topDownTriangleLight.png")

	fmt.Println()
	fmt.Println("All PNG files have been generated.")
}
